---
editor_options:
  markdown:
    wrap: 72
title: Contract Rates - Accessorial Analysis
---

# packages

```{r, echo = f}
library(bigrquery)
library(DBI)
library(dplyr)

bqcon <- dbConnect(
  bigrquery::bigquery(),
  project = "freightwaves-data-science"
)

bj2 <- dbGetQuery(bqcon, "Select *
From(
  select *, 
  case 
    when transportation_mode_description in ('TRUCKLOAD (DRY VAN)', 'TRUCKLOAD', 'MOTOR', 'BROKER') then 'VAN'
    when transportation_mode_description = 'TRUCKLOAD (TEMP-CONTROLLED)'then 'REEFER'
    else
      'Other'
    end
    as mode
    from `freightwaves-data-factory.warehouse.beetlejuice`)
where mode in ('VAN', 'REEFER') and ship_date >= '2022-05-01'
")
```

#Check most common accessorials

```{r, echo = F}
accessorial_table <- bj2 %>% 
  mutate(system_type = toupper(system_type)) %>%
  group_by(accessorial_charge_description, mode, system_type) %>% 
  tally() %>% arrange(desc(n)) %>% 
print(accessorial_table)
```

#Create base / fuel / accessorial individual line item charge columns

```{r, echo = F}
base_total <- bj2 %>% filter(origin_country_code %in% c("USA", "US")) %>%
  mutate(LOH = cut(distance,
                   c(0,100, 250, 500, 750, 1000, 1500,10000),
                   labels = c('City', 'Short', 'Mid', 'Tweener', 'Long', 'Extra-Long', 'Cross Country'))) %>% 
  group_by(cass_shipment_id, mode, origin_postal_code, destination_postal_code, LOH, shipper_master_code, ship_date) %>%
  filter(!grepl('BASE', accessorial_charge_description)) %>%
  summarize(non_base_total = sum(accessorial_charge_amount, na.rm=T), total = max(amount_paid)) %>%
  mutate(Base_Rate = total - non_base_total) %>%
  mutate(Base_Rate = ifelse(is.na(Base_Rate), 0, Base_Rate))


fuel_total <- bj2 %>% filter(origin_country_code %in% c("USA", "US")) %>% 
  group_by(cass_shipment_id, mode, origin_postal_code, destination_postal_code) %>%
  filter(grepl('FUEL|ENERGY', accessorial_charge_description)) %>%
  summarize(fuel_total = sum(accessorial_charge_amount, na.rm=T)) %>%
  mutate(fuel_total = ifelse(fuel_total < 0, 0, fuel_total))

other_total <- bj2 %>% filter(origin_country_code %in% c("USA", "US")) %>% 
  group_by(cass_shipment_id, mode, origin_postal_code, destination_postal_code) %>%
  filter(!grepl('BASE|FUEL|ENERGY', accessorial_charge_description)) %>%
  summarize(other_total = sum(accessorial_charge_amount)) %>%
  mutate(other_total = ifelse(other_total < 0, 0, other_total))

targeted_total <- bj2 %>% filter(origin_country_code %in% c("USA", "US")) %>% 
  group_by(cass_shipment_id, mode, origin_postal_code, destination_postal_code) %>%
  filter(grepl('PICKUP|DELIVERY|LOADING|USED|TOLL|TAX|CUSTOMS|TAX|BORDER|COMPLIANCE|MANAGEMENT|MISCELL|DUTY|CARBON', accessorial_charge_description)) %>%
  summarize(targeted_total = sum(accessorial_charge_amount, na.rm=T))%>%
  mutate(targeted_total = ifelse(is.na(targeted_total), 0, targeted_total))

all_data <- base_total %>% 
  select(cass_shipment_id,ship_date, mode,LOH, shipper_master_code, origin_postal_code, destination_postal_code, total, non_base_total, Base_Rate) %>% 
  left_join(., fuel_total, by = c('cass_shipment_id', 'mode', 'origin_postal_code', 'destination_postal_code')) %>% 
  left_join(., other_total, by = c('cass_shipment_id', 'mode', 'origin_postal_code', 'destination_postal_code')) %>% 
  left_join(., targeted_total, by = c('cass_shipment_id', 'mode', 'origin_postal_code', 'destination_postal_code')) %>%
  mutate(Base_Rate = ifelse(is.na(Base_Rate), 0, Base_Rate),
         fuel_total = ifelse(is.na(fuel_total), 0, fuel_total),
         targeted_total = ifelse(is.na(targeted_total), 0, targeted_total)) %>%
  mutate(Base_Fuel = Base_Rate + fuel_total,
         Base_Fuel_Targeted = Base_Rate + fuel_total + targeted_total) %>% 
  #rename(mode = mode.x) %>%
  mutate(origin_zip3 = substr(origin_postal_code, 1, 3), 
         dest_zip3 = substr(destination_postal_code, 1, 3)) %>%
  select(cass_shipment_id,ship_date, mode, LOH,shipper_master_code, origin_zip3, dest_zip3, total, non_base_total, Base_Rate, fuel_total, other_total, targeted_total, Base_Fuel, Base_Fuel_Targeted)
```

#Variance by mode by lane for each 
```{r, echo = F} 

good_data <- all_data %>% 
  mutate(lane = paste(origin_zip3, dest_zip3, sep = ':')) %>% 
  filter(Base_Rate > 0 & Base_Rate <= 5000 &
           Base_Fuel > 0 & Base_Fuel <= 10000 &
           Base_Fuel_Targeted >= 0 & Base_Fuel_Targeted <= 20000) %>%
  filter(fuel_total >= 0 & fuel_total <= 5000 &
           other_total >= 0 & other_total <= 10000 &
           targeted_total >= 0 & targeted_total <= 10000)

volume_lanes <- good_data %>% mutate(week = strftime(ship_date, '%V%')) %>% group_by(mode, origin_zip3, dest_zip3, LOH, week) %>%
  summarize(Load_Count = n(), Carrier_Count = length(unique(shipper_master_code))) %>%
  filter(Carrier_Count >= 3) %>% mutate(lane = paste(origin_zip3, dest_zip3, sep = ':'))


use_data <- good_data %>% filter(lane %in% volume_lanes$lane)

var_df <- use_data %>%
  group_by(mode, origin_zip3, dest_zip3, LOH) %>%
  summarize(Var_Base = var(Base_Rate), 
            Var_Base_Fuel = var(Base_Fuel),
            Var_Base_Fuel_Targeted = var(Base_Fuel_Targeted),
            Var_Total = var(total),
            Count = n())

#Average Lane Variance by mode w LOH
med_var_df_LOH <- var_df %>% 
  filter(Var_Base != 0 & Var_Base_Fuel != 0 & Var_Base_Fuel_Targeted != 0) %>% 
  group_by(mode, LOH) %>%
  summarize(`Lane Count` = n(), 
            Med_Var_Base = median(Var_Base, na.rm = T), 
            Med_Var_Base_Fuel = median(Var_Base_Fuel, na.rm = T),
            Med_Var_Base_Fuel_Targeted = median(Var_Base_Fuel_Targeted, na.rm = T),
            Med_Var_Total = median(Var_Total, na.rm = T)
           ) %>% 
  tidyr::pivot_longer(., cols = 4:ncol(.), names_to = 'Rate Type', values_to = 'Median Variance') %>%
  mutate(`Median Variance` = round(`Median Variance`, 0)) %>%
  arrange(mode, LOH, `Median Variance`)

med_var_df <- var_df %>% 
  filter(Var_Base != 0 & Var_Base_Fuel != 0 & Var_Base_Fuel_Targeted != 0) %>% 
  group_by(mode) %>%
  summarize(`Lane Count` = n(), 
            Med_Var_Base = median(Var_Base, na.rm = T), 
            Med_Var_Base_Fuel = median(Var_Base_Fuel, na.rm = T),
            Med_Var_Base_Fuel_Targeted = median(Var_Base_Fuel_Targeted, na.rm = T),
            Med_Var_Total = median(Var_Total, na.rm = T)
           ) %>% 
  tidyr::pivot_longer(., cols = 3:ncol(.), names_to = 'Rate Type', values_to = 'Median Variance') %>%
  mutate(`Median Variance` = round(`Median Variance`, 0))

print(med_var_df)
```



```{r}
med_var_df_LOH_plot <- med_var_df_LOH %>% 
  ggplot(aes(LOH, `Median Variance`, fill=`Rate Type`)) +
  geom_bar(stat="identity", position="dodge") +
  theme_classic()
med_var_df_LOH_plot
```

```{r}
med_var_df_plot <- med_var_df %>% 
  ggplot(aes(mode, `Median Variance`, fill=`Rate Type`)) +
  geom_bar(stat="identity", position="dodge") +
  theme_classic()
med_var_df_plot
```

