---
editor_options:
  markdown:
    wrap: 72
title: Contract Rates - Accessorial Analysis
---

# Packages

```{r, echo = f}

library(bigrquery)
library(DBI)
library(dplyr)

```

# BQ connection

```{r}

bqcon <- dbConnect(
  bigrquery::bigquery(),
  project = "freightwaves-data-science"
)

```

# BQ pull data

```{r, echo = f}

bj <- dbGetQuery(bqcon,
                 
  "with data as (
    select
      cass_shipment_id
      ,ship_date
      ,shipper_master_code
      ,substring(origin_postal_code, 1, 3) as origin_zip3
      ,substring(destination_postal_code, 1, 3) as dest_zip3
      ,upper(system_type) as system_type
      ,case 
        when transportation_mode_description in ('TRUCKLOAD (DRY VAN)', 'TRUCKLOAD', 'MOTOR', 'BROKER') then 'VAN'
        when transportation_mode_description = 'TRUCKLOAD (TEMP-CONTROLLED)'then 'REEFER'
        else 'OTHER'
        end as mode
      ,case
        when distance < 100 then 'City'
        when distance < 250 then 'Short'
        when distance < 500 then 'Mid'
        when distance < 750 then 'Tweener'
        when distance < 1000 then 'Long'
        when distance < 1500 then 'Extra-long'
        else 'Cross-country'
        end as LOH
      ,case
        when upper(accessorial_charge_description) like '%ENERGY%SUR%(FUEL%' then 'ENERGY SURCHARGE (FUEL ADJUSTMENT FACTOR)'
        when upper(accessorial_charge_description) like '%ENERGY%CH%(FUEL%' then 'ENERGY CHARGE (FUEL ADJUSTMENT FACTOR)'
        when upper(accessorial_charge_description) like '%ENERGY%SUR%' then 'ENERGY SURCHARGE'
        when upper(accessorial_charge_description) like '%ENERGY%CH%' then 'ENERGY CHARGE'
        when upper(accessorial_charge_description) like '%ENERGY%' then 'ENERGY OTHER'
        when upper(accessorial_charge_description) like '%FUEL%SUR%' then 'FUEL SURCHARGE'
        when upper(accessorial_charge_description) like '%SUR%FUEL%' then 'FUEL SURCHARGE'
        when upper(accessorial_charge_description) like '%FUEL%CH%' then 'FUEL CHARGE'
        when upper(accessorial_charge_description) like '%FUEL%TAX%' then 'FUEL TAX'
        when upper(accessorial_charge_description) like 'FUEL' then 'FUEL'
        when upper(accessorial_charge_description) like '%FUEL%ADJ%' then 'FUEL ADJUSTMENT'
        when upper(accessorial_charge_description) like '%DELIVERY%FUEL%' then 'FUEL DELIVERY'
        when upper(accessorial_charge_description) like '%ORIGIN%FUEL%' then 'FUEL ORIGIN'
        when upper(accessorial_charge_description) like '%DESTINATION%FUEL%' then 'FUEL DESTINATION'
        when upper(accessorial_charge_description) like '%FUEL%' then 'FUEL OTHER'
        else upper(accessorial_charge_description)
        end as accessorial_charge_description
      ,accessorial_charge_amount
      ,amount_paid
      
    from `freightwaves-data-factory.warehouse.beetlejuice`
    where origin_country_code in ('USA', 'US') and
      ship_date > '2022-05-01' and
      (upper(accessorial_charge_description) like '%FUEL%'
      or upper(accessorial_charge_description) like '%ENERGY%'
      or upper(accessorial_charge_description) like '%BASE%')
  )
  
  select
    *
  from data
  where mode in ('VAN', 'REEFER')
    and ship_date > '2022-05-01'"
    
  )

```

# Check most common accessorials

```{r, echo = F}

accessorial_table <- bj %>% 
  group_by(accessorial_charge_description, mode, system_type) %>% 
  tally() %>% arrange(desc(n)) %>% 
print(accessorial_table)

```

# Create base charge column

```{r, echo = F}

base_total <- bj %>%
  group_by(cass_shipment_id) %>%
  filter(!grepl('BASE', accessorial_charge_description)) %>%
  summarize(non_base_total = sum(accessorial_charge_amount, na.rm=T), total = max(amount_paid)) %>%
  mutate(base_rate = total - non_base_total)

all_data <- bj %>%
  left_join(., base_total, by=c('cass_shipment_id')) %>%
  mutate(non_base_total = ifelse(is.na(non_base_total), 0, non_base_total),
         total          = ifelse(is.na(total), amount_paid, total),
         base_rate      = ifelse(is.na(base_rate), amount_paid, base_rate))

good_data <- all_data %>% 
  mutate(lane = paste(origin_zip3, dest_zip3, sep = ':')) %>% 
  filter(base_rate > 0 & base_rate <= 5000 &
           total > 0 & total <= 10000)

```

# Summary stats

```{r}


  

```








#Variance by mode by lane for each 

```{r, echo = F} 

good_data <- all_data %>% 
  mutate(lane = paste(origin_zip3, dest_zip3, sep = ':')) %>% 
  filter(Base_Rate > 0 & Base_Rate <= 5000 &
           Base_Fuel > 0 & Base_Fuel <= 10000 &
           Base_Fuel_Targeted >= 0 & Base_Fuel_Targeted <= 20000) %>%
  filter(fuel_total >= 0 & fuel_total <= 5000 &
           other_total >= 0 & other_total <= 10000 &
           targeted_total >= 0 & targeted_total <= 10000)

volume_lanes <- good_data %>% mutate(week = strftime(ship_date, '%V%')) %>% group_by(mode, origin_zip3, dest_zip3, LOH, week) %>%
  summarize(Load_Count = n(), Carrier_Count = length(unique(shipper_master_code))) %>%
  filter(Carrier_Count >= 3) %>% mutate(lane = paste(origin_zip3, dest_zip3, sep = ':'))


use_data <- good_data %>% filter(lane %in% volume_lanes$lane)

var_df <- use_data %>%
  group_by(mode, origin_zip3, dest_zip3, LOH) %>%
  summarize(Var_Base = var(Base_Rate), 
            Var_Base_Fuel = var(Base_Fuel),
            Var_Base_Fuel_Targeted = var(Base_Fuel_Targeted),
            Var_Total = var(total),
            Count = n())

#Average Lane Variance by mode w LOH
med_var_df_LOH <- var_df %>% 
  filter(Var_Base != 0 & Var_Base_Fuel != 0 & Var_Base_Fuel_Targeted != 0) %>% 
  group_by(mode, LOH) %>%
  summarize(`Lane Count` = n(), 
            Med_Var_Base = median(Var_Base, na.rm = T), 
            Med_Var_Base_Fuel = median(Var_Base_Fuel, na.rm = T),
            Med_Var_Base_Fuel_Targeted = median(Var_Base_Fuel_Targeted, na.rm = T),
            Med_Var_Total = median(Var_Total, na.rm = T)
           ) %>% 
  tidyr::pivot_longer(., cols = 4:ncol(.), names_to = 'Rate Type', values_to = 'Median Variance') %>%
  mutate(`Median Variance` = scales::comma(`Median Variance`))

med_var_df <- var_df %>% 
  filter(Var_Base != 0 & Var_Base_Fuel != 0 & Var_Base_Fuel_Targeted != 0) %>% 
  group_by(mode) %>%
  summarize(`Lane Count` = n(), 
            Med_Var_Base = median(Var_Base, na.rm = T), 
            Med_Var_Base_Fuel = median(Var_Base_Fuel, na.rm = T),
            Med_Var_Base_Fuel_Targeted = median(Var_Base_Fuel_Targeted, na.rm = T),
            Med_Var_Total = median(Var_Total, na.rm = T)
           ) %>% 
  tidyr::pivot_longer(., cols = 3:ncol(.), names_to = 'Rate Type', values_to = 'Median Variance') %>%
  mutate(`Median Variance` = scales::comma(`Median Variance`))

print(med_var_df)
```



```{r}

```